name: gaif
channels:
  - anaconda
  - conda-forge
dependencies:
  - python>3.11
  - click
  - python-dotenv
  - jupyterlab
  - loguru
  - pandas
  - numpy
  - gradio
  - seaborn
  - matplotlib
  - scikit-learn